/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mavalu.dtool.panels;

import br.com.mavalu.dtool.DtoolJFrame;
import br.com.mavalu.dtool.control.DtoolLogControl;
import br.com.mavalu.dtool.control.DtoolQueryControl;
import br.com.mavalu.useful.QueryTableModel;
import java.util.logging.Level;
import javax.swing.JDialog;
import javax.swing.JTable;

/**
 *
 * @author q1D55V6G
 */
public class QueryList extends javax.swing.JPanel {

   private final JDialog jDialog;
   private final DtoolJFrame dtoolJFrame;

   /**
    * Creates new form QueryList
    */
   public QueryList(JDialog jd, DtoolJFrame dt) {
      initComponents();
      jDialog = jd;
      dtoolJFrame = dt;

      DtoolQueryControl.loadQueries(jTable1);

   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      jDialog1 = new javax.swing.JDialog();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      jPanel1 = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();

      javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
      jDialog1.getContentPane().setLayout(jDialog1Layout);
      jDialog1Layout.setHorizontalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jDialog1Layout.setVerticalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      jTable1.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jTable1MousePressed(evt);
         }
      });
      jScrollPane1.setViewportView(jTable1);

      jPanel1.setLayout(new java.awt.GridBagLayout());

      jButton1.setText("Fechar");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.ipadx = 1;
      gridBagConstraints.ipady = 1;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.weighty = 6.0;
      gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
      jPanel1.add(jButton1, gridBagConstraints);

      jButton2.setText("Remover");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 5;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.ipadx = 1;
      gridBagConstraints.ipady = 1;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.weighty = 6.0;
      gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
      jPanel1.add(jButton2, gridBagConstraints);
      jButton2.getAccessibleContext().setAccessibleDescription("");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addGap(0, 0, 0)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0))
      );
   }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int row = jTable1.getSelectedRow();

       String foo = (String) jTable1.getModel().getValueAt(row, 1);
       dtoolJFrame.operationControl(dtoolJFrame.OP_SET_QUERY, true, new String[]{foo});

    }//GEN-LAST:event_jTable1MouseClicked

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int rows[] = jTable1.getSelectedRows();

      if (rows.length == 0) {
         DtoolLogControl.log("Selecione uma lenha para exclusão", Level.WARNING);
         return;
      }

      QueryTableModel model = (QueryTableModel) jTable1.getModel();
      DtoolQueryControl.removeQuerys(rows, model);
      DtoolQueryControl.loadQueries(jTable1);
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
      if (evt.getClickCount() == 2) {
         jDialog.setVisible(false);
      }
   }//GEN-LAST:event_jTable1MousePressed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JDialog jDialog1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   // End of variables declaration//GEN-END:variables
}
